name:                advent-of-code-y2021-haskell
version:             0.1.0.0
github:              "gagandeepkalra/advent-of-code-y2021-haskell"
license:             BSD3
author:              "Gagandeep Kalra"
maintainer:          "Gagandeep Kalra"
copyright:           "2019 Gagandeep Kalra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gagandeeepkalra/advent-of-code-y2021-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- split

library:
  source-dirs: src

executables:
  advent-of-code-y2021-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2021-haskell

tests:
  advent-of-code-y2021-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2021-haskell
